### ISSUE TITLE
hello，可以问下你是哪个学院的吗？

### ISSUE THREAD

**Issue by onns** [zoam/xmu-thesis-grd#1]
你的模板格式里我仔细核对了一下有些小问题，想知道是否每个学院要求不同。

顺便你介意我帮你一起修改这个模板吗？（方便之后的人用之类的）

**Comment by zoam** [comment]
我是信息学院的。欢迎一起修改。那个链接是研究生院的。它上面的格式要求感觉是针对所有研究生的吧？

**Comment by onns** [comment]
> 我是信息学院的。欢迎一起修改。那个链接是研究生院的。它上面的格式要求感觉是针对所有研究生的吧？

封面英文标题是`三号`，你写的`小二`，还有一些别的。你开放个编辑权限给我？或者像BIT那边弄个组织？

**Comment by zoam** [comment]
我不太会用 GitHub 而且现在我有事情要忙，晚上我研究一下怎么弄这个组织。

**Comment by Crescentz** [comment]
请问你们开始一起修改了么

**Comment by Crescentz** [comment]
> > 我是信息学院的。欢迎一起修改。那个链接是研究生院的。它上面的格式要求感觉是针对所有研究生的吧？
> 
> 封面英文标题是`三号`，你写的`小二`，还有一些别的。你开放个编辑权限给我？或者像BIT那边弄个组织？

请问改过来了吗，你是硕or 博

**Comment by zoam** [comment]
> > > 我是信息学院的。欢迎一起修改。那个链接是研究生院的。它上面的格式要求感觉是针对所有研究生的吧？
> > 
> > 
> > 封面英文标题是`三号`，你写的`小二`，还有一些别的。你开放个编辑权限给我？或者像BIT那边弄个组织？
> 
> 请问改过来了吗，你是硕or 博

onns 已经把他发现的问题修改好了。如果你有发现什么问题的话可以加进来一起修改。我是博士。

**Comment by Crescentz** [comment]
> > > > 我是信息学院的。欢迎一起修改。那个链接是研究生院的。它上面的格式要求感觉是针对所有研究生的吧？
> > > 
> > > 
> > > 封面英文标题是`三号`，你写的`小二`，还有一些别的。你开放个编辑权限给我？或者像BIT那边弄个组织？
> > 
> > 
> > 请问改过来了吗，你是硕or 博
> 
> onns 已经把他发现的问题修改好了。如果你有发现什么问题的话可以加进来一起修改。我是博士。

师兄好，请问如果想要添加特殊字体，比如说有些“需要”添加 几个特别的字（洛马，泰文，藏语之类，只是偶尔几个）（非宋体，黑体等常规字体），应该如何操作呢

**Comment by zoam** [comment]
这个我也不是很懂，囧。我也只会改改模上一些比较基础的东西。目前我没时间研究这个，在赶一个报告 PPT。网上应该有挺多资料的，比如这个链接 https://liam.page/2017/09/17/LaTeX-multi-lingual/
