### ISSUE TITLE
新更新的cls里面章和下面正文之间会不会间距太大了？

### ISSUE THREAD

**Issue by ZhichaoOuyang** [zoam/xmu-thesis-grd#10]
![image](https://user-images.githubusercontent.com/51399917/118085912-bdf15000-b3f5-11eb-9729-a7c39aa4c26f.png)

![image](https://user-images.githubusercontent.com/51399917/118085984-d82b2e00-b3f5-11eb-9c24-7cfad472a756.png)

word模版里好像是章段后18磅。
章直接接节的是不是又把段后和段前叠加起来更大了

**Comment by ZhichaoOuyang** [comment]
![image](https://user-images.githubusercontent.com/51399917/118086265-407a0f80-b3f6-11eb-9407-df87bf41a29a.png)
![image](https://user-images.githubusercontent.com/51399917/118086282-45d75a00-b3f6-11eb-9d99-c85523358139.png)
一个是这里latex生成的间距，
一个是word模版的

**Comment by onns** [comment]
Duplicate of #8

**Comment by onns** [comment]
好像是的，我们再调整下，后面在#8中讨论，这俩是同一个问题。
