### ISSUE TITLE
一些细节问题

### ISSUE THREAD

**Issue by xiecon** [zoam/xmu-thesis-grd#11]
1. 公式的引用是否需要“（）”
![image](https://user-images.githubusercontent.com/49284675/118256754-6d0a5600-b4e0-11eb-9aeb-48f8ed6d3c8f.png)
2. 摘要、目录、致谢的页眉中间需要空格
3. 页眉英文不需要使用全大写
`\fancyhead[CO]{\zihao{5} \songti \nouppercase\leftmark}`

**Comment by zoam** [comment]
1. 公式引用需要自己输括号。这个在其他模板中应该也是一样的。
2. 这个空格是我特意去掉。理论上页眉不该有空格。真的需要空格也行，我搞个选项吧。我个人不想要这个空格。按我个人理解，Word 模板之所以会有这个空格，是因为它的页眉只能保持与章节标题一致，想去也去不掉。
3. 页眉英文这个大写可以去掉。在下个版本中修正。
