### ISSUE TITLE
图/表与正文空隙很大的问题你们觉得如何解决比较合理？

### ISSUE THREAD

**Issue by onns** [zoam/xmu-thesis-grd#12]
今年答辩老师普遍提出的一个问题，学长你可以把GitHub里的一个discussion功能打开，这其实不属于issue。

如果latex觉得当前页不够排版下一页的某些内容（比如标题、长公式等），就将多的内容放在下一页，使得当前页会有很多的空行。

![Snipaste_2021-05-15_09-17-20](https://user-images.githubusercontent.com/16622934/118343946-64586500-b55e-11eb-93f5-a0c4034851c1.png)

这个在word里不会出现，因为word可以强制排版。其实我觉得latex的才是规范，但是这个结论好像老师们不接受。

所以想问问大家有没有什么合理的解决方案

**Comment by ZhichaoOuyang** [comment]
\vspace{-3em或其它单位}调整

**Comment by onns** [comment]
好吧，这个是调整图表与正文的距离的。

**Comment by ZhichaoOuyang** [comment]
图跟图之间也可以的，只要你调的比例足够大，他就不会空很多了。
这个的问题就在于万一模版又大改，可能你调的东西又要改。
所以我前几天从另一个模版改到这个模版的时候，调这些图的位置和间距也花了巨多的时间。
平时我们写英文论文都是用这个来调。

**Comment by onns** [comment]
嗯，感谢，确实只能挨个调过去了。

**Comment by onns** [comment]
![Screen Shot 2021-05-15 at 12 11 26](https://user-images.githubusercontent.com/16622934/118347592-13089f80-b577-11eb-8333-8e04a8199ed4.png)
![Screen Shot 2021-05-15 at 12 13 54](https://user-images.githubusercontent.com/16622934/118347593-1439cc80-b577-11eb-97b5-d0f44025823f.png)

效果不错，感谢老哥

**Comment by ZhichaoOuyang** [comment]
客气

**Comment by zoam** [comment]
查了一下，似乎在空隙大的图之后插入这两句代码就可以了。你们试试？
```tex
\vfill
\rule[\baselineskip]{0pt}{\baselineskip}
```
这是我测试的效果
![image](https://user-images.githubusercontent.com/5723558/118352704-58d46080-b595-11eb-966f-81f8c6ff4ff8.png)

**Comment by onns** [comment]
这个貌似是调整题目与表格/图片之间距离的。

**Comment by zoam** [comment]
可能也有调整题目与表格/图片之间距离的作用，不用这个两个命令之前长这样。

![image](https://user-images.githubusercontent.com/5723558/118356063-110a0500-b5a6-11eb-9513-8930b68c8278.png)

跟上面的图对比一下，可以发现这两个命令确实是有作用的。可能得加个花括号限制一下作用范围？

**Comment by onns** [comment]
好的，我试试，我今天调那个vspace调了一下午😂

**Comment by ZhichaoOuyang** [comment]
> 好的，我试试，我今天调那个vspace调了一下午😂

这种加花括号里面一般填啥？有例子给一个嘛

**Comment by zoam** [comment]
好像上面那个方法不通用。你们试试把
```tex
\makeatletter
\setlength{\@fptop}{0pt}% default is 0\p@ \@plus 1fil
\setlength{\@fpsep}{\floatsep}% default is 8\p@ \@plus 2fil
%\setlength{\@fpbot}{0pt plus 1fil}% default is 0\p@ \@plus 1fil
\makeatother
```
放到导言区试试？我这里测试感觉效果还不错。如果你们也没问题的话，我想把开启/关闭这个东西做成一个选项。

**Comment by ZhichaoOuyang** [comment]
> 好像上面那个方法不通用。你们试试把
> 
> ```
> \makeatletter
> \setlength{\@fptop}{0pt}% default is 0\p@ \@plus 1fil
> \setlength{\@fpsep}{\floatsep}% default is 8\p@ \@plus 2fil
> %\setlength{\@fpbot}{0pt plus 1fil}% default is 0\p@ \@plus 1fil
> \makeatother
> ```
> 
> 放到导言区。我这里测试感觉效果还不错。如果你们也没问题的话，我想把开启/关闭这个东西做成一个选项。

这个我试了一下，好像没啥效果，是放在cls文件里吗？我在cls和demo.tex放了都试了下，好像还是不能解决。

**Comment by zoam** [comment]
我的错。我以为放在导言区也可以。我是直接放在章节里
![image](https://user-images.githubusercontent.com/5723558/118390877-0b72f480-b664-11eb-88fc-d3830fc542f1.png)

这是使用后的效果
![image](https://user-images.githubusercontent.com/5723558/118390895-1af23d80-b664-11eb-8231-b473736c75cd.png)
