### ISSUE TITLE
"学位论文答辩委员会名单"页可否自动生成

### ISSUE THREAD

**Issue by steermomo** [zoam/xmu-thesis-grd#14]
用tabularx 直接做了一个表进去，效果也还行，应该比word->pdf->latex方便一些

![image](https://user-images.githubusercontent.com/10905619/118392428-48db8000-b66c-11eb-9c58-3d7b5854196d.png)

**Comment by zoam** [comment]
这效果确实不错。行距可能还需要调整一下。那个占位用的 `-` 号也得去掉。

**Comment by steermomo** [comment]
#15
