### ISSUE TITLE
正文字体有误

### ISSUE THREAD

**Issue by onns** [zoam/xmu-thesis-grd#17]
正文的字体好像跑出来是仿宋😂

**Comment by zoam** [comment]
我这里测试正文是宋体。你的意思是指部分正文字体会变成仿宋吗？还是说所有的都是仿宋？
![image](https://user-images.githubusercontent.com/5723558/118610990-f080bb80-b7ee-11eb-82ea-c62a7dca9a6d.png)

**Comment by onns** [comment]
![6641621323696_ pic_hd](https://user-images.githubusercontent.com/16622934/118611780-c7145f80-b7ef-11eb-991f-3520af9ccc0d.jpg)
![6651621323747_ pic_hd](https://user-images.githubusercontent.com/16622934/118611821-d09dc780-b7ef-11eb-8763-fc2bc6f8849d.jpg)
后面的`是`是宋体

**Comment by zoam** [comment]
明白了。可能是字体没弄对。宋体的字体文件是 ttc 格式的，可能不能按照 ttf 的方法来加载。顺便说一下，这个 FandoSong 其实不是仿宋。。。它也是宋体的一种。

**Comment by zoam** [comment]
你在设置c ls文件中，设置中文字体的附近加下面这句代码再试试。
```tex
\setCJKmainfont{SimSun.ttc}
```

**Comment by onns** [comment]
等等，我在调页眉

**Comment by onns** [comment]
话说你知道我图里画圈那个地方咋调嘛？
![Screen Shot 2021-05-18 at 16 26 20](https://user-images.githubusercontent.com/16622934/118618323-1493cb00-b7f6-11eb-95e9-546a6063434a.png)

**Comment by onns** [comment]
`headheight = 2cm,%`这个值好像对页眉完全没影响，我设置成10都没效果

**Comment by zoam** [comment]
你要不看看这个宏包的文档？
https://ctan.org/pkg/geometry?lang=en

**Comment by onns** [comment]
哈哈哈哈我正在看
https://texdoc.org/serve/geometry/0

**Comment by onns** [comment]
问题基本找到了。。。
正文的字体行距没有应用到第一行上。。
就是行距应该是给文字上下留下距离，好像我们没有

**Comment by zoam** [comment]
这可能是由于 LaTeX 跟 Word 在排版方面的处理不太一样。之前那个段前段后设置它们也不一样。我估计我们得想一些变通的方案。

**Comment by onns** [comment]
解决方法只能是在top和headsep里同步补偿1.5倍浮动应该给的距离（headheight没用）
![Screen Shot 2021-05-18 at 17 04 55](https://user-images.githubusercontent.com/16622934/118623950-4eb39b80-b7fb-11eb-86d6-6ff29f97dc1d.png)
上面算是解决了（我补偿了0.1cm）

但下面也需要设置。。而且这个值很难确定，还有页号的位置其实也有问题
![Screen Shot 2021-05-18 at 17 06 56](https://user-images.githubusercontent.com/16622934/118624157-7acf1c80-b7fb-11eb-99a3-58eac2a155cd.png)

**Comment by zoam** [comment]
下面的值为什么难确定呢？

**Comment by onns** [comment]
1. 页号的值我不知道是咋确定的。
2. 上方的缺口我觉得就是半个行距的差距，但是下面差的有点大。。。

**Comment by zoam** [comment]
footskip 可以调页号的位置。多出来的一行是否可以通过调节 bottom 来去掉？

**Comment by onns** [comment]
可以，那脚注也是需要调的吧？

**Comment by onns** [comment]
只是感觉不科学，为什么上面只少半个行距空隙，下面少那么多，不可解释。

**Comment by zoam** [comment]
脚注好调吗？
Word 排版是玄学，LaTeX 排版也差不太多。

**Comment by zoam** [comment]
不过感觉最好还是不动 bottom 好，估计会有很多问题。也有可能是 Word 设置了“对齐到网格”的问题

**Comment by zoam** [comment]
取消了对齐到网络，那么 Word 的下面的空间完全塞得下一行。

![image](https://user-images.githubusercontent.com/5723558/118628306-11510d00-b7ff-11eb-9452-27502586c8c3.png)

**Comment by zoam** [comment]
取消对齐到网格，并删掉撑大行距的公式，Word 就能多塞下一行。

![image](https://user-images.githubusercontent.com/5723558/118628686-6ee55980-b7ff-11eb-9303-2377c0726fbe.png)

**Comment by onns** [comment]
![Screen Shot 2021-05-18 at 18 18 32](https://user-images.githubusercontent.com/16622934/118634908-9c350600-b805-11eb-92aa-1542b634d145.png)

**Comment by zoam** [comment]
对了，你把这句也放进 cls 文件。之前的段落间距有点问题。
```tex
%% 设置段落间距
\setlength{\parskip}{0em}
```

**Comment by onns** [comment]
> 对了，你把这句也放进 cls 文件。之前的段落间距有点问题。
> 
> ```
> %% 设置段落间距
> \setlength{\parskip}{0em}
> ```

随便放吗，还是放在哪，你咋没改cls文件

**Comment by zoam** [comment]
这些修改我还没 push 上去。你先随便放，我到时候一起 push 上去

**Comment by onns** [comment]
为什么我改chapter的before skip没效果啊😂😂

**Comment by zoam** [comment]
确实 chapter 的 before skip 改成 0 也还有一大段空白，莫名其妙

**Comment by onns** [comment]
哈哈哈哈我改成section的了
![Screen Shot 2021-05-18 at 20 39 11](https://user-images.githubusercontent.com/16622934/118652600-57b36580-b819-11eb-989e-7eca2647dfd3.png)
感觉可以了

**Comment by zoam** [comment]
赞！

**Comment by zoam** [comment]
对了，好像正文的行距好像跟 Word 模板的对不上，你要不也一起调一下？Word 模板设置了对齐到网格，实际行距会比设置的要大一些。

**Comment by onns** [comment]
刚刚问辅导员了，这个问题。。。自己统一一下就行，感觉今天算是白改了。。。

**Comment by zoam** [comment]
也不算白改，毕竟你收获了知识。。。

**Comment by onns** [comment]
其实那个行间距间隔确实要改，太贴顶上了

**Comment by zoam** [comment]
嗯，原来的太丑了

**Comment by onns** [comment]
ok我把数值更新上GitHub了
上方的数值我觉得是要改的， 下面的数值你觉得要改吗

**Comment by zoam** [comment]
会动到很多东西吗？如果不多的话可以改。

**Comment by zoam** [comment]
那要不先不改？

**Comment by onns** [comment]
那行

**Comment by zoam** [comment]
没看到你上传的更新啊

**Comment by onns** [comment]
```
\renewcommand\theequation{\arabic{chapter}-\arabic{equation}}
```
这个还是改一下比较好，应该用一行。我没push，这不是在问你意见

**Comment by zoam** [comment]
那就改吧。

**Comment by onns** [comment]
> ```
> \renewcommand\theequation{\arabic{chapter}-\arabic{equation}}
> ```
> 
> 这个还是改一下比较好，应该用一行。我没push，这不是在问你意见

这个我们好像被答辩老师说了，你下次更新的时候记得改一下这个就好～

**Comment by onns** [comment]
\setCJKmainfont{SimSun}[AutoFakeSlant,AutoFakeBold]
加了句这个确实解决问题了，感谢～

**Comment by zoam** [comment]
> > ```
> > \renewcommand\theequation{\arabic{chapter}-\arabic{equation}}
> > ```
> >
> > 这个还是改一下比较好，应该用一行。我没push，这不是在问你意见
> 
> 这个我们好像被答辩老师说了，你下次更新的时候记得改一下这个就好～

你说的是公式里序号的分隔符啊。这个我倒是没注意到。答辩老师真细心。

**Comment by onns** [comment]
> > > ```
> > > \renewcommand\theequation{\arabic{chapter}-\arabic{equation}}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 这个还是改一下比较好，应该用一行。我没push，这不是在问你意见
> > 
> > 
> > 这个我们好像被答辩老师说了，你下次更新的时候记得改一下这个就好～
> 
> 你说的是公式里序号的分隔符啊。这个我倒是没注意到。答辩老师真细心。

对啊，我说的是分隔符，我之前就觉得长😂
