### ISSUE TITLE
参考文献格式

### ISSUE THREAD

**Issue by xueyinhualuo** [zoam/xmu-thesis-grd#18]
感谢大佬的工作！

我看学校给的参考文献格式
`[15]	Atkinson J B, Becker J, Demtröder W. Experimental observation of the a3u state of Na2[J]. Chem Phys Lett, 1982, 87:92-97.`
人名都是小写的，但是\RequirePackage{gbt7714}的bst里面设定的是大写

或许可以考虑加入本地bst，然后将
`#1 'uppercase.name :=`
改为
`#0 'uppercase.name :=`

cls里面改用
`\bibliographystyle{reference/gbt7714-numerical}`
对下面语句取消注释
`\RequirePackage[numbers,square,comma,super,sort&compress]{natbib}`

**Comment by onns** [comment]
我在本地确实是这样做的，https://github.com/zoam/xmu-thesis-grd/discussions/16

**Comment by xueyinhualuo** [comment]
> 我在本地确实是这样做的，#16

但是去除不详后似乎跟写作指南违背，写作指南有要求符合GB/T 7714—2015，现在变成用natbib了
`（2） 无出版者的中文文献著录[出版者不详]，外文文献著录[s.n.]。无出版者的电子资源可省略此项。`
`（3） 无出版地的中文文献著录[出版地不详]，外文文献著录[S.l.]。无出版地的电子资源可省略此项。`

**Comment by onns** [comment]
我有点没理解你说的`现在变成用natbib了`是啥意思？

那好吧，还是不去掉了😂

**Comment by xueyinhualuo** [comment]
natbib.sty跟gbt7714-numerical.bst都是管理文献格式的，好像会冲突。如果取消注释natbib会按natbib的格式去走，gbt7714-numerical.bst就不起作用了。但是学校又要gbt7714的格式

**Comment by xueyinhualuo** [comment]
我还试了一下如果只是加载本地bst，不去取消natbib的注释的话，就变成人名引用而不是数字引用了，目前不知道怎么解决。明明跟之前 \RequirePackage{gbt7714} \bibliographystyle{gbt7714-numerical} 用的同一个bst，但是效果不一样

**Comment by onns** [comment]
我对比过了，应该没有影响。

**Comment by onns** [comment]
如果你觉得不放心，可以改源文件试试

```
D:\texlive\2021\texmf-dist\bibtex\bst\gbt7714\
```

**Comment by xueyinhualuo** [comment]
> 如果你觉得不放心，可以改源文件试试
> 
> ```
> D:\texlive\2021\texmf-dist\bibtex\bst\gbt7714\
> ```

感谢指导，我目前还是按照我上面说的那种直接用本地的`reference/gbt7714-numerical`和`natbib`，等提交时候不行了再改吧
