### ISSUE TITLE
中文摘要的背面没有页眉而且没有显示页码

### ISSUE THREAD

**Issue by zz0807** [zoam/xmu-thesis-grd#19]

**Comment by zoam** [comment]
奇怪，我这里没发现这个问题。
![image](https://user-images.githubusercontent.com/5723558/119220189-d8c17400-bb1b-11eb-84b5-9bc46492d43d.png)
![image](https://user-images.githubusercontent.com/5723558/119220230-21792d00-bb1c-11eb-9bf2-fff326b9acc6.png)

你能提供详细一点的信息吗？比如系统、Tex Live 版本、截图之类的？

**Comment by zz0807** [comment]
![image](https://user-images.githubusercontent.com/11792573/119220791-cac12280-bb1e-11eb-916b-66d20021fd74.png)
我是用overleaf编译的，就这个背面是全部空白的
![image](https://user-images.githubusercontent.com/11792573/119220808-e2001000-bb1e-11eb-8b28-a870a3f93c64.png)
还有下一页的英文摘要，从页码从3开始，没有2

**Comment by zoam** [comment]
你是否启用了双面打印选项 `twoside`？如果是的话这个结果是符合预期的，因为摘要需要在页码为单数的那一面开始。如果摘要背面是空白的则不需要任何文字，包括页眉页脚啥的。

**Comment by zz0807** [comment]
是的，我开了双面打印，您看看我的第二个截图，英文摘要的页码不应该是2吗

**Comment by zoam** [comment]
双面打印的时候就应该是III啊。abstract 需要在奇数页，前面的空白页也算一页，只是不显示页码。
