### ISSUE TITLE
中英文目录页少了英文目录索引

### ISSUE THREAD

**Issue by zz0807** [zoam/xmu-thesis-grd#20]
![image](https://user-images.githubusercontent.com/11792573/119230369-75046e80-bb4e-11eb-8d4b-938453948b5b.png)
![image](https://user-images.githubusercontent.com/11792573/119230382-8188c700-bb4e-11eb-8419-1a4cd255da21.png)
有中英文摘要的索引，但是只有中文目录的索引，没有英文的

**Comment by zoam** [comment]
因为信息学院给的模板就长这样，所以为了和模板保持一致就没加。不知道你是哪个学院的？如果真的有需要的话，我可以教你怎么加。

**Comment by zz0807** [comment]
> 因为信息学院给的模板就长这样，所以为了和模板保持一致就没加。不知道你是哪个学院的？如果真的有需要的话，我可以教你怎么加。

好的，谢谢大佬回复，我也是信息学院的，那我再去确认一下格式
