### ISSUE TITLE
英文目录页码不对

### ISSUE THREAD

**Issue by onlyvae** [zoam/xmu-thesis-grd#21]
![2](https://user-images.githubusercontent.com/25417261/119291210-a8471a80-bc80-11eb-9e30-5abb60daa14a.png)
![3](https://user-images.githubusercontent.com/25417261/119291216-a9784780-bc80-11eb-9a0d-27f47614b1be.png)
![1](https://user-images.githubusercontent.com/25417261/119291219-aa10de00-bc80-11eb-8173-d923d57c3087.png)
英文目录的content页码不对，既不是中文目录的页码也不是英文目录的页码

**Comment by onns** [comment]
提问之前看一下更新日志，已经更新了的
