### ISSUE TITLE
最后一页学术成果好像要再加一页背面的空白页(加页眉页脚）

### ISSUE THREAD

**Issue by zz0807** [zoam/xmu-thesis-grd#25]
https://github.com/zoam/xmu-thesis-grd/issues

**Comment by onns** [comment]
```latex
% 致谢
\include{chapters/acknowledgements}

% 发表文章目录
\include{chapters/publications}

\cleardoublepage

```

**Comment by onns** [comment]
马上会发一版新版

**Comment by zoam** [comment]
> 马上会发一版新版

新版应该不用加这个 `\cleardoublepage` 吧？

**Comment by zz0807** [comment]
谢谢，辛苦大佬

**Comment by onns** [comment]
> > 马上会发一版新版
> 
> 新版应该不用加这个 `\cleardoublepage` 吧？

应该是要的

**Comment by zoam** [comment]
> > > 马上会发一版新版
> > 
> > 
> > 新版应该不用加这个 `\cleardoublepage` 吧？
> 
> 应该是要的

手动加跟没内容应该是一样的。为了稳妥起见，那我还是写到 `demo.tex` 里吧。

**Comment by onns** [comment]
> > > > 马上会发一版新版
> > > 
> > > 
> > > 新版应该不用加这个 `\cleardoublepage` 吧？
> > 
> > 
> > 应该是要的
> 
> 手动加跟没内容应该是一样的。为了稳妥起见，那我还是写到 `demo.tex` 里吧。

没东西是没东西，但是得有新的那一页呀，不然就是整本都是奇数页数。。

**Comment by zoam** [comment]
> > > > > 马上会发一版新版
> > > > 
> > > > 
> > > > 新版应该不用加这个 `\cleardoublepage` 吧？
> > > 
> > > 
> > > 应该是要的
> > 
> > 
> > 手动加跟没内容应该是一样的。为了稳妥起见，那我还是写到 `demo.tex` 里吧。
> 
> 没东西是没东西，但是得有新的那一页呀，不然就是整本都是奇数页数。。

因为这个学术成果在最后面啊。奇数页有东西，偶数页不管是没有东西还是打印空白页，效果是一样的。因为纸张背面是偶数页，不管你打不打印东西它都在。

**Comment by onns** [comment]
电子版！

**Comment by zoam** [comment]
电子版还要求这个？学院也太魔怔了吧。
