### ISSUE TITLE
没有出现参考文献

### ISSUE THREAD

**Issue by shenshikexmu** [zoam/xmu-thesis-grd#28]
直接下载“xmu-thesis-grd-master”，在Mac和win10上都试，生成的pdf和自带的pdf比，少了参考文献。求解答

**Comment by onns** [comment]
编译链设置对了吗？2021年6月21日 06:13，张欣 ***@***.***>写道：

直接下载“xmu-thesis-grd-master”，在Mac和win10上都试，生成的pdf和自带的pdf比，少了参考文献。求解答

**Comment by shenshikexmu** [comment]
对不起，什么是“编译链接”

**Comment by onns** [comment]
你是用什么命令编译pdf的

**Comment by shenshikexmu** [comment]
XeLaTeX   用的TeXShop

**Comment by onns** [comment]
根目录下有`xmu-thesis-run.sh`和`xmu-thesis-run.cmd`分别对应macos和windows。你直接运行这两个命令就可以了。

**Comment by shenshikexmu** [comment]
ok，有参考文献了，感谢
