### ISSUE TITLE
参考文献格式

### ISSUE THREAD

**Issue by onns** [zoam/xmu-thesis-grd#3]
如果出版地不详会有`[S.l.: s.n.]`这个输出，我感觉有点多余，应该删除，你觉得呢？

**Comment by onns** [comment]
删除位置我是找到了，但是有具体的规范吗我是想说

**Comment by zoam** [comment]
学院的写作指南里有参考文献的规范。我不知道你说的出版地是什么。是指会议举行的地方还是出版社？

**Comment by onns** [comment]
```
[5] Scovanner P, Ali S, Shah M. A 3-dimensional sift descriptor and its application to action recognition [C]. Proceedings of the 15th ACM international conference on Multimedia. [S.l.: s.n.], 2007: 357– 360.
```

出版社

**Comment by onns** [comment]
> 学院的写作指南里有参考文献的规范。我不知道你说的出版地是什么。是指会议举行的地方还是出版社？

我知道有，我的同学也说其实不应该有这个地方（如果参考文献没有，应该不显示，而不是显示`[S.l.: s.n.]`）

**Comment by zoam** [comment]
你这个是会议。应该是会议举行的地方吧？会议论文应该没有出版社这个说法。我之前写期刊论文，会议举行的地方缺失的时候，确实是空白的。我也没搞懂这个模板是怎么处理的。不过bib里会议举行的地方如果缺失的话一般都是能在网上查到的。遇到缺失我都是手动查然后手动在bib里面补上去。建议还是查一下而不是直接删除。

**Comment by onns** [comment]
好吧，那我暂时不push上来了～

**Comment by zoam** [comment]
比如你这条参考文献可以在这里找到 https://dl.acm.org/doi/proceedings/10.1145/1291233
然后在 bib 里加一项 `address = {{Augsburg, Germany}},`

**Comment by onns** [comment]
> 比如你这条参考文献可以在这里找到 https://dl.acm.org/doi/proceedings/10.1145/1291233
> 然后在 bib 里加一项 `address = {{Augsburg, Germany}},`

确实是可以，但是我感觉大家不会去挨个找的。。。

**Comment by onns** [comment]
今年的格式要求真的好严格，我希望从我们这届起大家的latex模板都能统一哈哈哈，我觉得你这个模板看着就很清晰而且可改性很高，如果有机会和学院弄成官方的样式都可以省的大家自己改格式了。

**Comment by zoam** [comment]
按照期刊论文的规范就是得有会议地址的。我其实还没开始写毕业论文，所以也没去了解具体的规范，你要删掉也没事。我个人感觉影响不大。

**Comment by onns** [comment]
没事，这个我不改，按照目前的来。

**Comment by zoam** [comment]
关于这个模板我确实是花了挺多心思来整理的。本人的 LaTeX 的水平也不高。希望更多人能参与进来，能造福更多人吧。

**Comment by onns** [comment]
是的，感谢🙏
我能做的就是帮你完善可能存在的问题并且让更多的人知道哈哈哈！
