### ISSUE TITLE
专著集引用格式与规范不符

### ISSUE THREAD

**Issue by huanlin9669** [zoam/xmu-thesis-grd#32]
在引用类型为inproceddings时，生成引用结果如下：
[1] VASWANI A, SHAZEER N, PARMAR N, et al. Attention is all you need[C]//Proceedings of NeurIPS 2017. 2017: 5998-6008.
但正确的格式应该是：
[1] Vaswani A, Shazeer N, Parmar N, et al. Attention Is All You Need[C]. Proceedings of NeurIPS 2017. 2017: 5998-6008.
人名不应该是全大写；标题首字母需大写；且全部用“.”分隔而不是"//"

**Comment by zoam** [comment]
人名不全大写比较好办。改一个值就好了。但实际上全大写才是 [国家标准GB/T 7714—2015](https://www.schinafish.cn/fileNFSCKX/cms/news/info/upload/e54b3af5-3908-412f-9922-b46874177503.pdf)，学院这种首字母大写的反而是非标准的。我觉得还是按照学院的来吧，稍后就修改一下。但是，后面这个我感觉就不好整了。我得研究研究。

**Comment by zoam** [comment]
感觉你第二个说的也不太对。应该不用改。信息学院给的[参考文献模板](https://github.com/zoam/xmu-thesis-grd/blob/6282dbc93bca3c158802527eddae37738578cc8b/doc/%E5%8D%9A%E5%A3%AB%E5%AD%A6%E4%BD%8D%E8%AE%BA%E6%96%87%E6%A8%A1%E6%9D%BF/11.%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%EF%BC%88%E7%A4%BA%E4%BE%8B%EF%BC%89.doc)里，会议论文就是用双斜杠来分隔的
![image](https://user-images.githubusercontent.com/5723558/156746824-67953cff-75e1-40d3-b194-3cab4b223f7b.png)

**Comment by huanlin9669** [comment]
学院提供的[论文格式规范](https://informatics.xmu.edu.cn/system/_content/download.jsp?urltype=news.DownloadAttachUrl&owner=1480852315&wbfileid=4478181)里写的是：“专著、论文集、学位论文、研究报告――［序号］主要责任者.文献题名[文献类型标识]. 出版地：出版者，出版年. 起止页码（任选）.”
不过如果参考文献模板里有双斜杠形式的话，那就先按照这样来吧

**Comment by zoam** [comment]
按我理解，可能它这句话可能没总结好。如果全用句点的话。“Proceedings of NeurIPS 2017”属于哪个什么？感觉应该归到文献题名中，但是前面已经有一个“Attention is all you need[”作为文献题名了。
