### ISSUE TITLE
请问现在给图加脚注的命令是什么呢

### ISSUE THREAD

**Issue by huanlin9669** [zoam/xmu-thesis-grd#34]
如题，之前似乎是\captionwithsource{}{}，但现在不能用了。

**Comment by zoam** [comment]
之前是什么时候？我不记得有提供过这个命令。。。我看别人好像是caption和source分开的
https://tex.stackexchange.com/questions/95029/add-source-to-figure-caption

**Comment by huanlin9669** [comment]
在答疑群21年5月的群公告里。我按照上面链接里的方案作了下修改：
`\newcommand*{\captionsource}[2]{
  \caption[{#1}]{#1
  \vspace{6pt}\\
  \small #2
  }
}`
现在这样写会导致source和caption的格式完全相同，但学院的要求是这样的：
![image](https://user-images.githubusercontent.com/69391792/156928530-fa723c4e-d153-4752-a98e-85792a26efc4.png)
不知道要怎么解决左对齐、字号和加粗的问题呢？

**Comment by zoam** [comment]
我没加过你说的答疑群。我添加了一个 `captionwithsource` 命令，你测试看看有没有问题。

**Comment by huanlin9669** [comment]
有点小问题，source的句首没有空两格
![image](https://user-images.githubusercontent.com/69391792/157016353-d38c6107-c1c5-457c-9f6e-c300abce65e7.png)

**Comment by zoam** [comment]
这样子？
![image](https://user-images.githubusercontent.com/5723558/157019078-d79b0e98-fd75-42aa-8a0e-9315b255cb84.png)

**Comment by huanlin9669** [comment]
嗯嗯，这样看着没什么问题

**Comment by zoam** [comment]
我把版本推送上去了。你自己再测一下。这个 Issue 我就先关了。
