### ISSUE TITLE
关于英文目录中附录的问题      

### ISSUE THREAD

**Issue by Xuling-re** [zoam/xmu-thesis-grd#38]
给附录添加英文标题后，生成的英文目录显示的是Chapter A，而不是Appendix A
![1677652277516](https://user-images.githubusercontent.com/61627010/222062666-65e19831-d785-46df-b6e3-4c48da7b1ff1.jpg)

**Comment by zoam** [comment]
![image](https://user-images.githubusercontent.com/5723558/222077167-69dbc926-cb9e-4ca2-9ba3-4f5863929221.png)
我这边不会出现这个问题。你给附录加英文标题的时候可以按下面这样做。

```tex
\chapter{关于XXX的证明}
\addcontentsline{etoc}{chapter}{\sffamily Appendix A~~Proof of XXXX}

附录相关内容…
```

**Comment by Xuling-re** [comment]
可以了，感谢老哥
