### ISSUE TITLE
和学院网站上提供的模板有什么区别

### ISSUE THREAD

**Issue by tinywaferShark** [zoam/xmu-thesis-grd#40]
经济学院和信息学院都发了自己的官方版本，想知道和现在这个仓库的有什么关系；或者哪个更好一点呢

**Comment by zoam** [comment]
这个仓库跟官方的没有关系。官方的我没用过。你可以自己对比一下排版效果，我估计两者差不太多，都是照着 Word 版本改的。

**Comment by tinywaferShark** [comment]
好的 谢谢啦
