### ISSUE TITLE
\textbf 无法加粗正文

### ISSUE THREAD

**Issue by Yeah2333** [zoam/xmu-thesis-grd#41]
![image](https://user-images.githubusercontent.com/22851247/229118371-8d900484-62d3-4df6-8ff7-96686f6515f0.png)

**Comment by zoam** [comment]
我这边无法复现。你用的是哪个版本的 TextLive？
<img width="769" alt="image" src="https://user-images.githubusercontent.com/5723558/229119161-46b0fde2-fb86-4566-bd91-3b5896d51640.png">

**Comment by note286** [comment]
我也无法复现，Windows 10，TeX Live 2023，XeLaTeX编译。

```latex
\documentclass{xmu-thesis-grd}
\begin{document}
1.点云体素化
1.\textbf{点云体素化}
\end{document}
```

![image](https://user-images.githubusercontent.com/16207292/229119518-1356d9d2-5aee-4bbe-b0ba-53d0aecc458d.png)

**Comment by zoam** [comment]
或者说你认为加粗还不够粗？这个倒是可以调节的。在 xmu-thesis-grd.cls 中改这几行的 `AutoFakeBold={2}`。将这里的 2 改成你想要的数值，比如 2.5、3之类的。
<img width="472" alt="image" src="https://user-images.githubusercontent.com/5723558/229119547-25d21bb4-b138-4e20-89bb-89576afcf63b.png">

**Comment by note286** [comment]
`thuthesis`的是3，可以参考一下。

https://github.com/tuna/thuthesis/blob/900988bb93eae5395adc9a590132fb1262429222/thuthesis.dtx#L2563-#L2574

**Comment by Yeah2333** [comment]
破案了。。。实际上是由加粗的，但不知道为啥vscode里面的pdf看起来没加粗，下载下来用pdf expert可以看出加粗。
感谢各位大佬迅速回复
![image](https://user-images.githubusercontent.com/22851247/229122264-13f8653b-f0dc-48ed-84ea-9c2f9a3d0904.png)
