### ISSUE TITLE
关于图片中字图的画法

### ISSUE THREAD

**Issue by Yeah2333** [zoam/xmu-thesis-grd#42]
我这边是用subfigure画子图回报错，想问一下怎样才能正确画子图？

**Comment by note286** [comment]
请阅读`subcaption`宏包文档，或者参考 https://github.com/note286/xduts/discussions/40#discussioncomment-4955967 。

**Comment by note286** [comment]
刚好在电脑边，O(∩_∩)O哈哈~

非必要宏包直接写死就会有这种问题，我个人倾向于不内置，仅适配样式。用户习惯用啥就用啥。

**Comment by zoam** [comment]
第一次搞模板，没啥经验。下次有机会得考虑一下这么干。

**Comment by Yeah2333** [comment]
感谢各位大佬，我这边搞ok了。非常感谢
