### ISSUE TITLE
正文内容被加粗

### ISSUE THREAD

**Issue by onns** [zoam/xmu-thesis-grd#7]
目前已知的bug是，正文内容会被莫名其妙的加粗到整页的结束。

暂时没定位到问题原因，我之前出现过，但是后来忘了，记录在这里，一是为了提醒大家查看一下类似的问题，方便定位；二是作为记录。

**Comment by ZhichaoOuyang** [comment]
一些表格用了resize有时候会导致它下面的字加粗

**Comment by onns** [comment]
> 一些表格用了resize有时候会导致它下面的字加粗

那你是咋解决的？再resize一下吗？

**Comment by ZhichaoOuyang** [comment]
> > 一些表格用了resize有时候会导致它下面的字加粗
> 
> 那你是咋解决的？再resize一下吗？

resize相当于把表格的字缩小，可以自定义表格里的字体。
比如用\footnotesize，或者更小的

\begin{table*}[ht]
\caption{x x x}
\begin{center}
\footnotesize
\begin{tabular}{|c|c|c|c|c|c|c|}
\hline

**Comment by onns** [comment]
查到了相关资料，这甚至不是ctex包的问题，是更上层的问题。。。

https://github.com/TheNetAdmin/zjuthesis/issues/24

可以试试这里的解决方案，我没试出来。

**Comment by onns** [comment]
问题解决@ZhichaoOuyang，换2021版本就可以了

**Comment by ZhichaoOuyang** [comment]
> 问题解决@ZhichaoOuyang，换2021版本就可以了

overleaf好像只有2020的，那只能用本地了。
不过我不用resize，其实也没这个问题了
