### ISSUE TITLE
英文目录有个地方有bug

### ISSUE THREAD

**Issue by ZhichaoOuyang** [zoam/xmu-thesis-grd#9]
![image](https://user-images.githubusercontent.com/51399917/117951900-33eaae00-b347-11eb-95f4-414832f354e1.png)

在学期间完成的相关学术成果的英文翻译后，页码会直接到下面一行去。
overlefa和本地好像都是这样

**Comment by xiecon** [comment]
把这个注释取消就不会了
```
%% 不允许断字（如果设置了断字的话，当英文目录标题过长并出现断字的时候，该标题的页码会跑到左边）
% \tolerance=1
% \emergencystretch=\maxdimen
% \hyphenpenalty=10000
% \hbadness=10000
```

**Comment by zoam** [comment]
![image](https://user-images.githubusercontent.com/5723558/117953418-96907980-b348-11eb-8c58-13631b838f64.png)

我在本地编译不会出现这个情况。英文断字了页码也不会跑到下一行的左边。既然大部分人有问题，那下次更新还是默认把这部分放出来吧。就是不断字英文间距太大会稍微丑一点。

**Comment by ZhichaoOuyang** [comment]
> 把这个注释取消就不会了
> 
> ```
> %% 不允许断字（如果设置了断字的话，当英文目录标题过长并出现断字的时候，该标题的页码会跑到左边）
> % \tolerance=1
> % \emergencystretch=\maxdimen
> % \hyphenpenalty=10000
> % \hbadness=10000
> ```

谢谢老哥

**Comment by ZhichaoOuyang** [comment]
> ![image](https://user-images.githubusercontent.com/5723558/117953418-96907980-b348-11eb-8c58-13631b838f64.png)
> 
> 我在本地编译不会出现这个情况。英文断字了页码也不会跑到下一行的左边。既然大部分人有问题，那下次更新还是默认把这部分放出来吧。就是不断字英文间距太大会稍微丑一点。

不允许断字还是会比跑到左边好看点，下次更新还是放出来吧～

**Comment by ZhichaoOuyang** [comment]
> ![image](https://user-images.githubusercontent.com/5723558/117953418-96907980-b348-11eb-8c58-13631b838f64.png)
> 
> 我在本地编译不会出现这个情况。英文断字了页码也不会跑到下一行的左边。既然大部分人有问题，那下次更新还是默认把这部分放出来吧。就是不断字英文间距太大会稍微丑一点。

但是英文摘要的时候就会好难看。。也是个问题

**Comment by onns** [comment]
我也不没有这个问题诶，可能是texlive版本问题

**Comment by ZhichaoOuyang** [comment]
老哥你是windows系统吗，texlive啥版本的，我是mac，用的texshop，不过也是基于texlive来的。
overleaf上面也是会有这个bug

**Comment by ZhichaoOuyang** [comment]
> 我也不没有这个问题诶，可能是texlive版本问题

https://github.com/zoam/xmu-thesis-grd/issues/9#issuecomment-839639327

**Comment by onns** [comment]
> 老哥你是windows系统吗，texlive啥版本的，我是mac，用的texshop，不过也是基于texlive来的。
> overleaf上面也是会有这个bug

版本是2020是吧？
我19的没问题，感觉和这个有关系，如果@zoam也是19那估计是这个原因了

**Comment by zoam** [comment]
我的是2020。不过我是 Linux 系统。

**Comment by zoam** [comment]
![image](https://user-images.githubusercontent.com/5723558/117966686-c777ab00-b356-11eb-92c7-7e7395d43c53.png)
这样子手动换行你们觉得能接受不？

**Comment by ZhichaoOuyang** [comment]
> ![image](https://user-images.githubusercontent.com/5723558/117966686-c777ab00-b356-11eb-92c7-7e7395d43c53.png)
> 这样子手动换行并保持其他地方的断字你们觉得能接受不？

可以，怎么实现的能教一下吗

**Comment by zoam** [comment]
![image](https://user-images.githubusercontent.com/5723558/117969522-18d56980-b35a-11eb-9e2a-214236b8c63a.png)
这里插入一个 \newline 其他地方保持不变。

**Comment by ZhichaoOuyang** [comment]
我第三章第四章的英文标题也很长，也会有这种页码跑到左边的问题。大佬这个方法好像不能兼容其他的英文标题？

**Comment by zoam** [comment]
你把过长的标题发出来，不然我也不好复现啊。

**Comment by ZhichaoOuyang** [comment]
> 你把过长的标题发出来，不然我也不好复现啊。

![image](https://user-images.githubusercontent.com/51399917/117971451-808cb400-b35c-11eb-891c-063bd1ff9df2.png)
还是在英文目录页里面出现的问题。

**Comment by ZhichaoOuyang** [comment]
我刚装了mac的texlive2021 也有这个bug，不知是不是版本问题了。

**Comment by zoam** [comment]
![image](https://user-images.githubusercontent.com/5723558/117971972-22140580-b35d-11eb-8760-6b6702f658b7.png)

![image](https://user-images.githubusercontent.com/5723558/117972089-4839a580-b35d-11eb-9785-ec54778cd2de.png)


目前搞不定这个bug。临时的解决方法只能每次手动插`\newline`了

**Comment by onns** [comment]
> 我刚装了mac的texlive2021 也有这个bug，不知是不是版本问题了。

我收回我的话，应该不是版本问题。

**Comment by ZhichaoOuyang** [comment]
> ![image](https://user-images.githubusercontent.com/5723558/117971972-22140580-b35d-11eb-8760-6b6702f658b7.png)
> 
> ![image](https://user-images.githubusercontent.com/5723558/117972089-4839a580-b35d-11eb-9785-ec54778cd2de.png)
> 
> 目前搞不定这个 bug。临时的解决方法只能是每次手动插 `\newline` 了

行谢谢老哥，那先这么处理

**Comment by zoam** [comment]
![image](https://user-images.githubusercontent.com/5723558/117985970-7e652e00-b339-11eb-9b9f-bc37ba560006.png)
我在 Windows 下用 TeX Live 2020 编译也没发现这个问题。但是 overleaf 上确实又有这个问题。搞不懂啊。

**Comment by ZhichaoOuyang** [comment]
没事，这个也可以接受。
再极端点，
\def\xmu@label@enpublications{Relevant Academic Achievements Completed During the Aca-\newline demic Period}
这么写就一样了。。傻瓜一点也没事

**Comment by onns** [comment]
感觉问题是，在生成目录的时候，计算距离的时候没考虑增加的`-`，所以算距离的时候没给够，所以页号被挤进下一行了

**Comment by zoam** [comment]
测试了一下。似乎用 `\linebreak` 的效果比 `\newline` 的效果好。用 `\linebreak` 换行后文字是两端对齐的，更美观。我觉得这个问题大体上算解决了吧。

这是 overleaf 上用 `\linebreak` 的测试效果：
![image](https://user-images.githubusercontent.com/5723558/118108064-20f0e000-b412-11eb-86cf-d9c339a56a42.png)

这是 overleaf 上用 `\newline` 的测试效果：
![image](https://user-images.githubusercontent.com/5723558/118108209-4e3d8e00-b412-11eb-98e6-59b81d559c7e.png)
